### ISSUE TITLE
No PDF found

### ISSUE THREAD

**Issue by Sush1090** [tub-hofmann/ecos-2024-template-paper#1]
Hello,
I am trying this on Overleaf but I get the following error: 
```
Emergency stop.              ./paper.preamble.tex‬
<*> paper.preamble.tex
                     
*** (job aborted, no legal \end found)

```

I am not able to debug the origin of this error.

**Comment by tub-hofmann** [comment]
Please invite me to your overleaf project.

email:
hofmann@iet.tu-berlin.de

We can take a look at the error together and chat within overleaf.

**Comment by tub-hofmann** [comment]
Overleaf menu option, main document was set to paper.preamble.tex. But it must be paper.tex.
